2020-10-18 11:51:44,413 - tools.log - ERROR - log - 第32行 - error
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 15, in process
    a=int('sss')
ValueError: invalid literal for int() with base 10: 'sss'
2020-10-20 17:58:13,020 - tools.log - ERROR - log - 第32行 - Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 19, in process
    result.data=int('sss')
ValueError: invalid literal for int() with base 10: 'sss'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 19, in process
    result.data=int('sss')
ValueError: invalid literal for int() with base 10: 'sss'
2020-10-21 00:46:45,110 - tools.log - ERROR - log - 第32行 - Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 20, in process
    result = int('sss')
ValueError: invalid literal for int() with base 10: 'sss'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 20, in process
    result = int('sss')
ValueError: invalid literal for int() with base 10: 'sss'
2020-10-21 01:27:32,368 - tools.log - ERROR - log - 第32行 - Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 24, in process
    result.data = self.parse(response)
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 63, in parse
    result[temp_dict['Slot']]=temp_dict
KeyError: 'Slot'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 24, in process
    result.data = self.parse(response)
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 63, in parse
    result[temp_dict['Slot']]=temp_dict
KeyError: 'Slot'
2020-10-21 01:31:46,185 - tools.log - ERROR - log - 第32行 - Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 24, in process
    result.data = self.parse(response)
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 63, in parse
    result[temp_dict['Slot']]=temp_dict
KeyError: 'Slot'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 24, in process
    result.data = self.parse(response)
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 63, in parse
    result[temp_dict['Slot']]=temp_dict
KeyError: 'Slot'
2020-10-21 01:32:50,413 - tools.log - ERROR - log - 第32行 - Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 24, in process
    result.data = self.parse(response)
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 64, in parse
    result[temp_dict['Slot']]=temp_dict
KeyError: 'Slot'
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 24, in process
    result.data = self.parse(response)
  File "C:\Users\Admin\PycharmProjects\CMDB\Controller\plugins\disk.py", line 64, in parse
    result[temp_dict['Slot']]=temp_dict
KeyError: 'Slot'
